name: dars_81_home
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  dio: ^5.6.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/svgs/
     - assets/imgs/
